name: RDP Direct Ngrok

on:
  workflow_dispatch:

jobs:
  build-rdp:
    runs-on: windows-latest
    steps:
      - name: Activer le bureau a distance (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Creer l'utilisateur Administrateur
        run: |
          net user AdminRdp Pass2026! /add
          net localgroup Administrators AdminRdp /add

      - name: Installer et configurer Ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/b3M4122dNVx/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "."
          .\ngrok.exe authtoken $env:NGROK_TOKEN
          cmd /c start .\ngrok.exe tcp 3389

      - name: Recuperer l'adresse IP/Port Ngrok
        run: |
          Start-Sleep -Seconds 5
          $response = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $publicUrl = $response.tunnels[0].public_url
          Write-Host "=========================================="
          Write-Host "VOTRE ADRESSE RDP : $publicUrl"
          Write-Host "=========================================="

      - name: Maintien du serveur actif (6h)
        run: |
          $i = 0
          while ($i -lt 360) {
            Start-Sleep -Seconds 60
            $i++
          }
