name: RDP Direct Ngrok

on:
  workflow_dispatch:

jobs:
  build-rdp:
    runs-on: windows-latest
    steps:
      - name: Activer le bureau a distance (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Creer l'utilisateur Administrateur
        run: |
          net user AdminRdp Pass2026! /add
          net localgroup Administrators AdminRdp /add

      - name: Installer Ngrok
        run: |
          choco install ngrok -y

      - name: Configurer et Lancer Ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok config add-authtoken $env:NGROK_TOKEN
          cmd /c start ngrok tcp 3389

      - name: Recuperer l'adresse IP/Port Ngrok
        run: |
          Start-Sleep -Seconds 6
          $response = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $publicUrl = $response.tunnels[0].public_url
          Write-Host "=========================================="
          Write-Host "VOTRE ADRESSE RDP : $publicUrl"
          Write-Host "=========================================="

      - name: Maintien du serveur actif (6h)
        run: |
          $i = 0
          while ($i -lt 360) {
            Start-Sleep -Seconds 60
            $i++
          }
